### ISSUE TITLE
Doesnt work as a drop in with level-sublevel

### ISSUE THREAD

**Issue by sveisvei** [Raynos/level-cache#3]
Tried to drop in level-cache instead of levelup with level-sublevel, and it doesnt work:

```
TypeError: Object object has no method 'on'
    at module.exports (../node_modules/level-sublevel/node_modules/level-hooks/index.js:67:6)
    at module.exports (../node_modules/level-sublevel/index.js:23:3)
```

Open for pull-requests, or is this module left for dead? If so, maybe get it removed from wiki and update readme.

I found this project via https://github.com/rvagg/node-levelup/wiki/Modules with this text:
`level-cache also doubles as in memory implementation of the LevelUP interface so that it can be used in unit tests or other situations where you want mocks.`

**Comment by Raynos** [comment]
PRs welcome :)

Although take a look at npm if there is a different caching module for levelup. In which case this should be deprecated in favor of that.

**Comment by sveisvei** [comment]
I guess using levelup with `{ db: require('memdown') }` as a backend is the way to go.

**Comment by Raynos** [comment]
Ah memdown exists, that's probably better :)
